version: '3.8'

services:
  db:
    image: postgres
    container_name: my_postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  fastapi:
    build:
      context: ./   # folder where your Dockerfile is
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "${FASTAPI_PORT}:8000"
    depends_on:
      - db
    restart: always

volumes:
  pg_data: